### ISSUE TITLE
Number inputs doesn't work with some non-english keyboards

### ISSUE THREAD

**Issue by marekhrabe** [wangjohn/creditly#2]
For example on my Czech keyboard I write number as <kbd>Shift</kbd> + <kbd>num</kbd> and probably some validation cancels that input so they are non-editable for me.

**Comment by wangjohn** [comment]
Interesting, thanks for pointing that out. Wasn't expecting these sorts of inputs for numbers. I'll be changing the way I do input validation which should hopefully fix this.

**Comment by marekhrabe** [comment]
Works for me now, seems like fixed
