### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cybernet** [wangjohn/creditly#3]
if possible, show the MasterCard OR ViSA OR Maestro Logo depending on the 1st number

**Comment by seize-the-dave** [comment]
https://en.wikipedia.org/wiki/Bank_card_number#Issuer_identification_number_.28IIN.29

**Comment by wangjohn** [comment]
Thanks for the feature request! This commit https://github.com/wangjohn/creditly/commit/230f401da3a015299951774eef9f80dd084ffc58 adds card number detection. 

Currently I'm supporting Visa, MasterCard, Discover, and AmericanExpress.

**Comment by cybernet** [comment]
you welcome סּ_סּ
